---
- name: Provisioning a new EC2 using Ansible playbook
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    keypair: demo
    instance_type: t2.micro
    image: ami-0e8d228ad90af673b  # Ensure this is valid for your region
    wait: yes
    group: webserver
    count: 1
    region: eu-west-2             # Ensure you are providing valid region
    security_group: ec2-security-group

  tasks:

    - name: Create a security group
      amazon.aws.ec2_security_group:
        name: "{{ security_group }}"
        description: Security Group for webserver Servers
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall

    - name: Launch the new EC2 Instance
      amazon.aws.ec2_instance:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        count: "{{ count }}"
        wait: "{{ wait }}"
      register: ec2

    - name: Debug EC2 Instances
      debug:
        var: ec2.instances

    - name: Add Tagging to EC2 instance
      amazon.aws.ec2_tag:
        resource: "{{ item.instance_id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: MyTargetEc2Instance
      with_items: "{{ ec2.instances }}"
      when: ec2.instances is defined and ec2.instances | length > 0